site_name: AdminService
site_url: https://amorafolf.github.io/AdminService
repo_name: AmoraFolf/AdminService
repo_url: https://github.com/AmoraFolf/AdminService

theme:
  icon:
    logo: material/database
    repo: fontawesome/brands/git-alt
  name: material
  favicon: docs/images/logos/AG_64.png
  palette:
  - scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Light mode
    primary: deep-purple
    accent: orange
  - scheme: default
    toggle:
      icon: material/toggle-switch
      name: Dark mode
    primary: deep-purple
    accent: orange

nav:
  - Home: index.md
  - Basics:
    - Setup: basics/setup.md
    - _aux: basics/_aux_module.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg